### PR TITLE
Adds Oil Rig icon

### LINKED ISSUE #5: oil-rig icon
#### Icon Request
Specific use case prompting request - Displaying oil rigs on a map, very useful for trying to encourage the oil industry to use our maps application

Icon concept & Reference Images:
[Example One ](https://t3.ftcdn.net/jpg/00/74/96/08/500_F_74960812_jYExS4hptO45OA7PpjMTyhw8bF1MyVMY.jpg)
[Example Two](https://cdn4.iconfinder.com/data/icons/energy-4/32/Energy-icons_oil-rig-512.png)

### PR DESCRIPTION
**Pull request by elizabetdev**
Closes #5.
 
This PR adds an Oil Rig icon.

Screenshot 2020-03-24 at 14 42 16

### CODE REVIEW

**Comment by nreese** [comment]
cc @Alex3k

**Comment by Alex3k** [comment]
Thanks @nreese, super excited about this!

**Comment by nreese** [comment]
> Thanks @nreese, super excited about this!

All thinks go to @miukimiu

**Comment by nreese** [comment]
Thanks for adding this icon. This is great. Can you add the `-es-` to the icon id and file names to avoid naming collisions if maki icons ever add an oil rig.

so `oil-rig-11` would be `oil-rig-es-11`

**Comment by Alex3k** [comment]
In that case, thank you @miukimiu! This will add that extra bit of detail that make us look even more awesome! It's really appreciated.

**Comment by nreese** [comment]
@nickpeihl do we need to re-generate SDF for this icon? How does that work?

**Comment by elizabetdev** [comment]
@nreese I just added the "es" to the icons, files names and IDs. 👍

**Comment by nickpeihl** [comment]
> @nickpeihl do we need to regenerate SDF for this icon? How does that work?

SDF icons get generated automatically when the release is published to NPM. 

Here's how I test the SDF version of icons locally:
1) `yarn prepublish && yarn link` in the maki directory
1) In the kibana directory, run `yarn kbn bootstrap` then `yarn link @elastic/maki`
1) Start kibana (`yarn es snapshot` and `yarn start`)

**Review by nickpeihl — CHANGES_REQUESTED** [review]
Wow! Thanks @miukimiu! 

I'm getting a strange result after processing this icon for web-gl in map. I wonder if the paths are reversed? This could also be a bug in my SDF generation code. I'll take a closer look, but let me know if you have any thoughts.

Screenshot_2020-03-24  Flights  Origin and Destination Flight Time - Elastic Kibana

**Comment by elizabetdev** [comment]
I think I caused the issue when I optimized the icons. @nickpeihl can you try again?

**Comment by nickpeihl** [comment]
> I think I caused the issue when I optimized the icons. @nickpeihl can you try again?

Looks better. Here's a screenshot from Kibana. 
Screen Shot 2020-03-24 at 9 51 35 AM

But this is how it looks to me in Inkscape. Is this intentional or is my Inkscape program screwing up?
Screen Shot 2020-03-24 at 9 52 21 AM

**Comment by elizabetdev** [comment]
I'll try to make it work first in kibana. I follow the steps you mentioned. I guess it's a problem with the way Figma is exporting the icon.

**Comment by elizabetdev** [comment]
I had to simplify the shape. This time I tested in Kibana.

The new icon:

Screenshot 2020-03-25 at 14 45 53

And how it looks like in Kibana:

Screenshot 2020-03-25 at 14 37 09

What do you think?

**Comment by nreese** [comment]
@miukimiu is there any way to get the original icon working in Kibana? I feel that the re-worked icon is hard to distinguish when the icon size is small.

**Comment by elizabetdev** [comment]
@nresse I think it looks weird in Kibana:
 
Screenshot 2020-03-25 at 16 48 07

What do you think?

**Comment by nreese** [comment]
Correct, the version in Kibana looks weird but the original drawings look great. Could the original drawings be re-worked to so there is no change between them and when they are imported in Kibana?

**Comment by nickpeihl** [comment]
The icon generation applies a sort of buffer to the path outlines. So I guess the crossing struts may be causing some of the weirdness. Perhaps we can remove some of the detail? Maybe fewer levels in the icon or thinner struts?

**Comment by elizabetdev** [comment]
@nickpeihl is right. The buffer is creating the issue. I tried to simplify the details. When the crosses are two small they don't look. For this reason, I just left one cross.

Screenshot 2020-03-25 at 18 06 40

**Comment by nreese** [comment]
I like that better then the oil platform but the icon looks like a water tower or light house when its small. Any way to have maybe two crosses and no open space towards the top of the tower?

**Comment by nreese** [comment]
how about something like this. The things on top are supposed to drops of oil

Screen Shot 2020-03-25 at 12 41 30 PM

**Comment by nickpeihl** [comment]
IMO, the latest design by @miukimiu lgtm. It follows the reference image in the [original issue](https://github.com/elastic/maki/issues/5) while being simple enough for rendering. Maybe @Alex3k can weigh in?

**Comment by Alex3k** [comment]
Hey folks, sorry for the delay! 

I think I prefer the latest design from @miukimiu, it looks really great.

**Comment by thomasneirynck** [comment]
Is this something we want to continue? would be nice to get in 7.8 still.. +1 on last icon fwiw @miukimiu

**Review by nickpeihl — APPROVED** [review]
lgtm! 

once merged, I can publish a new minor release to NPM and then we can bump the @elastic/maki dependency in kibana.

**Comment by elizabetdev** [comment]
Should I merge it?

**Comment by thomasneirynck** [comment]
@miukimiu yes, feel free to merge imho! if we get user feedback on making changes etc... we can always introduce a new one. thanks!

**Pull request merged**
